import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AppKitProvider } from "../../context";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await headers()).get("cookie");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-4 justify-center text-xl">
          <a href="/" className="text-white">
            Main
          </a>
          <a href="/dash" className="text-white">
            Dash
          </a>
        </nav>
        <div></div>
        <AppKitProvider cookies={cookie}>
          <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100">
            {children}
          </main>
        </AppKitProvider>
      </body>
    </html>
  );
}
